# Generated by Django 4.0.6 on 2022-07-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
